# Generated by Django 5.1.4 on 2026-02-17 19:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('duration', models.PositiveIntegerField(help_text='Duration value e.g. 1, 6, 24')),
                ('duration_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='hours', max_length=10)),
                ('data_limit_mb', models.PositiveIntegerField(blank=True, help_text='Data limit in MB. Leave blank for unlimited.', null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Upload speed limit in Kbps. Leave blank for unlimited.', null=True)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Download speed limit in Kbps. Leave blank for unlimited.', null=True)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('mikrotik_profile', models.CharField(blank=True, help_text='MikroTik hotspot profile name e.g. "1hr-plan"', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this plan prominently on portal')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
